apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: collab-container
  name: collab-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: collab-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/environement-virtualis-my-network: "true"
        io.kompose.service: collab-container
    spec:
      containers:
        - env:
            - name: PASSWORD_USER03
              value: password3
            - name: USERNAME_USER03
              value: user03
          image: karl123/pc-co
          name: workstationoceanet-collab
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: collab-data
      restartPolicy: Always
      volumes:
        - name: collab-data
          persistentVolumeClaim:
            claimName: collab-data
status: {}
