apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: it-container
  name: it-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: it-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/environement-virtualis-my-network: "true"
        io.kompose.service: it-container
    spec:
      containers:
        - env:
            - name: DONT_PROMPT_WSL_INSTALL
              value: "1"
            - name: PASSWORD_USER02
              value: password2
            - name: USERNAME_USER02
              value: user02
          image: karl123/pc-it
          name: workstationoceanet-it
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: it-data
      restartPolicy: Always
      volumes:
        - name: it-data
          persistentVolumeClaim:
            claimName: it-data
status: {}
