apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb-galera
  name: mariadb-galera
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb-galera
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/environement-virtualis-my-network: "true"
        io.kompose.service: mariadb-galera
    spec:
      containers:
        - env:
            - name: LDAP_BASE
              value: dc=example,dc=org
            - name: LDAP_BIND_DN
              value: cn=admin,dc=example,dc=org
            - name: LDAP_BIND_PASSWORD
              value: adminpassword
            - name: LDAP_URI
              value: ldap://openldap:1389
            - name: MARIADB_DATABASE
              value: customdatabase
            - name: MARIADB_ENABLE_LDAP
              value: "yes"
            - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
              value: backup-password
            - name: MARIADB_ROOT_PASSWORD
              value: root-password
            - name: MARIADB_USER
              value: customuser
          image: bitnami/mariadb-galera:latest
          name: mariadb-galera
          resources: {}
      restartPolicy: Always
status: {}
