apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openldap
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/environement-virtualis-my-network: "true"
        io.kompose.service: openldap
    spec:
      containers:
        - env:
            - name: LDAP_ADMIN_PASSWORD
              value: adminpassword
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_PASSWORDS
              value: password1,password2,password3
            - name: LDAP_USERS
              value: user01,user02,user03
          image: bitnami/openldap:2
          name: openldap
          ports:
            - containerPort: 1389
            - containerPort: 1636
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/openldap
              name: openldap-data
      restartPolicy: Always
      volumes:
        - name: openldap-data
          persistentVolumeClaim:
            claimName: openldap-data
status: {}
