apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: rh-container
  name: rh-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rh-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/environement-virtualis-my-network: "true"
        io.kompose.service: rh-container
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: password
            - name: PASSWORD_USER01
              value: password1
            - name: USERNAME_USER01
              value: user01
          image: karl123/pc-rh
          name: workstationoceanet-rh
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: rh-data
      restartPolicy: Always
      volumes:
        - name: rh-data
          persistentVolumeClaim:
            claimName: rh-data
status: {}
